### ISSUE TITLE
درخواست کمک در ionic 3

### ISSUE THREAD

**Issue by amin-setayeshfar** [hootan09/ionic2-cafebazaar-iap#1]
سلام اقا من دارم سعی میکنم به پرداخت کافه بازار وصل شم خیلی وقت هست دارم تلاش میکنم ولی نمیشه! عین کارایی که شما کردی رو کردم ولی اپ کرش میکنه وقتی توابع پرداخت شروع به فراخوانی میکنن. 
با اندروید استودیو مانیتور کردم یه ارور میده که یه جا میخواد یه مقدار نال رو به دابل کست کنه توی توابع خود لایبرری. اگه بتونین کمکم کنین خیلی ممنون میشم @hootan09

**Comment by hootan09** [comment]
سلام دوست عزیز اگه امکانش هست ارور رو بذار ببینم چی میگه.

**Comment by amin-setayeshfar** [comment]
برنامه بسته میشه درجا، و اندروید یه پاپ آپ باز میکنه که نوشته اپ هَز استاپد! همین
ولی با اندروید استودیو مانیتور که میکنم اینا رو نشون میده :
(همون تابع گرفتن محصولات رو که فراخوانی میکنم این رو میده)
`03-17 18:04:52.784 24532-24656/? E/AndroidRuntime: FATAL EXCEPTION: Thread-15
                                                   Process: ir.aka.azmanchekhabar, PID: 24532
                                                   java.lang.NumberFormatException: empty String
                                                       at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1071)
                                                       at java.lang.Double.parseDouble(Double.java:547)
                                                       at com.alexdisler.inapppurchases.SkuDetails.<init>(SkuDetails.java:47)
                                                       at com.alexdisler.inapppurchases.IabHelper.querySkuDetails(IabHelper.java:951)
                                                       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:563)
                                                       at com.alexdisler.inapppurchases.IabHelper.queryInventory(IabHelper.java:535)
                                                       at com.alexdisler.inapppurchases.IabHelper$2.run(IabHelper.java:630)
                                                       at java.lang.Thread.run(Thread.java:761)
03-17 18:04:52.837 433-2479/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
03-17 18:04:52.930 515-515/? E/SurfaceFlinger: CaptureScreen: layer name = ir.aka.azmanchekhabar/ir.aka.azmanchekhabar.MainActivity
03-17 18:04:53.200 1536-29599/? E/LocSvc_flp: I/===> int flp_get_batch_size() line 200 `

**Comment by amin-setayeshfar** [comment]
اقا اگه بتونی یه پروژه جدید بسازی و از اول همین کارا رو بکنی ببینی مشکل چیه بزرگترین لطف تاریخ رو بهم کردی 
ددلاینم 4 روز دیگس.. و واقعا خیلی سعی کردم و همه جا پرسیدم و نشده..

**Comment by hootan09** [comment]
بخدا فرصتشو ندارم تازه الان شرایط کار کردنش رو هم ندارم .خودم دلم میخواد کمکت کنم اما انگار نمیشه
قرار بود توی عید باهاش ور برم که نشد :(
این آی دی تلگرامه منه پیام بده صحبت کنیم @mam_niki

**Comment by BabakVandad** [comment]
سلام،
این مشکل به کجا رسید؟ راهی برای درست کردنش پیدا کردید؟

**Comment by amin-setayeshfar** [comment]
سلام..هنوز نه!! چند ماه هست ولش کردم..به زودی دوباره باید بشینم مشغولش شم..
ولی خیلییییی سعی کردم  . و سرچ..نشد

**Comment by BabakVandad** [comment]
ظاهرا این مسئله مربوط به یک باگ در هلپر معروف می‌شه.
IabHelper.java
یک [رپوی دیگه](https://github.com/j3k0/cordova-plugin-purchase) هست که اون هلپر رو اصلاح کردند و تا اینجا که من استفاده کردم کار می‌کنه.
همین کارهایی که اینجا توضیح دادید رو می‌شه با این یکی رپو هم انجام داد.
یانیک هم ازش پشتیبانی می‌کنه به [این ترتیب](https://ionicframework.com/docs/native/in-app-purchase-2/):

```
$ ionic cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="<ANDROID_BILLING_KEY>"
$ npm install --save @ionic-native/in-app-purchase-2
```
